### PR TITLE
[Fix] Fixed python3 issue with heartbeat

### PR DESCRIPTION
**Pull request by Robtom5**
Fixed issue with heartbeat relying on python2 behaviour of range

Addresses issues #33 and #34

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Drat! I just pushed a couple of commits to fix these, but I like your approach to handling the ranges better although `elem for ranges in heartbeat for elem in ranges` really hurts my head to parse.

I wonder if it would be worth deconstructing this to something like:

```
heartbeat = list(range(10, 0, -1))   # Rising beat
heartbeat += list(range(1, 5))       # Ba
heartbeat += list(range(5, 0, -1))   # Dum
heartbeat += list(range(1, 10))      # Falling beat
```

**Comment by Robtom5** [comment]
Yeah, double list comprehensions are a pain to parse. I've reworked it now

**Comment by Robtom5** [comment]
Conflict looks due to me forking before your changes to fix 34 went in. I think

**Comment by Robtom5** [comment]
Accidently closed

**Comment by Gadgetoid** [comment]
Merged and linted. You also had a small bug in the line `v = heart[x, y] * float(level/10)` which I fixed.

Thank you! It looks great.

**Pull request merged**
